### ISSUE TITLE
OpenModelica compatibility

### ISSUE THREAD

**Issue by thorade** [thorade/HelmholtzMedia#21]
Currently, trying to use HelmholtzMedia in OpenModelica results in errors similar to
`Variable fluidConstants[1].molarMass ...` and `Illegal subscript [1] for dimensions  in component ...`

**Comment by thorade** [comment]
Two constructs seem to cause most of the trouble:
- The [sat record](https://github.com/thorade/HelmholtzMedia/blob/master/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/package.mo#L48-L52) has two state records, so it is a record of records
  This should work, so it will hopefully be fixed on OM side (maybe 2018-Q1).
- The record [HelmholtzDerivs](https://github.com/thorade/HelmholtzMedia/blob/master/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/EoS/HelmholtzDerivs.mo) is setting some values.
  When instantiating HelmholtzDerivs f (e.g from [setHelmholtzDerivsSecond](https://github.com/thorade/HelmholtzMedia/blob/master/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/EoS/setHelmholtzDerivsSecond.mo), or from [setSat_T](https://github.com/thorade/HelmholtzMedia/blob/master/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/package.mo#L124-L140)) these values are not set, so e.g. MM is zero.
   Not sure whether this is legal and should be supported, or maybe it is wrong and should be rewritten!?

**Comment by thorade** [comment]
Nice progress with OpenModelica new frontend:
https://libraries.openmodelica.org/branches/newInst/HelmholtzMedia/HelmholtzMedia.html
https://libraries.openmodelica.org/branches/history/newInst/00_history.html
https://libraries.openmodelica.org/branches/history/newInst/HelmholtzMedia.svg
https://libraries.openmodelica.org/branches/history/newInst/HelmholtzMedia-recent.svg
Looks like it will work some time soon!

**Comment by casella** [comment]
@perost is working on improving function partial application and record constructor handling, which are key constructs for all Media library. I expect major improvements anytime soon

**Comment by perost** [comment]
> @perost is working on improving function partial application and record constructor handling, which are key constructs for all Media library. I expect major improvements anytime soon
I can't see any HelmholtzMedia models that fail because of those issues. Many of them fail because the backend uses an absurd amount of memory and is killed by Hudson, while others cause the Hudson job script to fail and not return any results at all (they seem to get stuck in a loop somewhere in the backend based on my testing).

From my quick testing it seems like all the models we test from HelmholtzMedia actually passes the new frontend. The few that also pass the backend seem to have some issues with package constants, an issue that also affects other libraries and will be fixed in due time. Otherwise it mostly looks like backend issues, at least superficially.

**Comment by casella** [comment]
@perost you are right. In the case of MSL there are many cases of back-end failure due to the fact that the new front end produces a different output than the old one, which is possibly correct but that the back-end cannot handle. In these cases, at least as an interim measure, we try to obtain the same output, even in those cases where this could be sub-optimal.

In this case, unfortunately, the old front-end could basically not handle these models (see [report](https://libraries.openmodelica.org/branches/master/HelmholtzMedia/HelmholtzMedia.html)), so we cannot try to restore the old front-end output, because there was none.

So, I agree with @perost that we should have to work a bit on the back-end.

@thorade, I currently see three failure modes in the library, I'll open tickets on them and put you in cc:.

**Comment by thorade** [comment]
Closing this, tracking the last few issues in #34 instead

**Comment by casella** [comment]
Looking at how long it took us to get through this I am a bit embarrassed, but it seems we are finally getting there 😃

**Comment by thorade** [comment]
https://en.wikipedia.org/wiki/Pareto_principle
https://en.wikipedia.org/wiki/Pareto_principle#In_computing
